In [1]:
"The notebook for selecting those regulation relations that are statistically significant that are inferred in 5th step"

'The notebook for selecting those regulation relations that are statistically significant that are inferred in 5th step'

In [18]:
"Parameters:fdrate: The false discover rate for identifying the significant regulations"

[1] "Parameters:fdrate: The false discover rate for identifying the significant regulations"

In [ ]:
"Return: The matrix that setting those non-significant regulations as 0"

[1] "Return: The matrix that setting those non-significant regulations as 0"

In [6]:
fdrate<-0.05

In [7]:
setwd('/Users/fz2gz/Desktop/project/Frustration_paper/Frus_github/result')

In [8]:
library(locfdr)
library(reticulate)

In [2]:
np <-import("numpy")


F_sparse<-np$load('dyn_EG_F.npy')
F_data<-F_sparse[,3]
print(dim(F_sparse))
w <- locfdr(F_data,bre=max(ceiling(1e-3*length(F_data)),100),df=10,nulltype=1,plot=1)
#     hist(F_sparse[,3],breaks=100)
F_sparse[,3][which(w$fdr>=fdrate)]<-0
hist(F_sparse[,3],breaks=100)
np$save(file.path(getwd(),'sparse_EG_F.npy'),F_sparse)
print(length(which(w$fdr<=fdrate)))

SyntaxError: invalid syntax (1905005641.py, line 1)

In [3]:
import numpy as np

F_sparse = np.load("result/dyn_EG_F.npy")

print(F_sparse.shape)
print(F_sparse[:5])
print(F_sparse.dtype)

(543169, 3)
[[ 0.          0.          0.        ]
 [ 0.          1.          0.10079146]
 [ 0.          2.          0.05150289]
 [ 0.          3.          0.08055559]
 [ 0.          4.         -0.01486201]]
float64
